// UET Bus Route Info - Official Route Dataset

const UET_DATA = {
  campuses: [
    {
      id: "ksk",
      name: "KSK / New Campus",
      shortName: "KSK Campus",
      location: "Kala Shah Kaku, GT Road, Sheikhupura",
      lat: 31.7295,
      lng: 74.2985,
      description: "UET New Campus (KSK) located on GT Road, Kala Shah Kaku."
    },
    {
      id: "main",
      name: "Main Campus (GT Road)",
      shortName: "Main Campus",
      location: "GT Road, Near Railway Station, Lahore",
      lat: 31.5794,
      lng: 74.3562,
      description: "UET Main Campus located on Grand Trunk Road, Lahore."
    }
  ],

  transportContact: {
    chairman: "Mr. M. Mushtaq",
    phone: "0304-0165776",
    office: "Transport Office, UET New Campus",
    timing: "08:00 AM - 04:00 PM (Mon-Fri)"
  },

  notices: [
    {
      id: 1,
      title: "Morning Bus Departure Timings",
      date: "Spring Semester 2026",
      category: "Schedule",
      content: "All morning buses arrive strictly by 07:45 AM (Main Campus) and 07:50 AM (KSK Campus). Students are advised to arrive at their respective stops 5-10 minutes prior to scheduled pickup."
    },
    {
      id: 2,
      title: "Main Campus Updated Routes (1 to 22)",
      date: "Official Update",
      category: "Routes",
      content: "All 22 morning routes for Main Campus GT Road have been updated with complete stop sequences and morning pickup timings."
    },
    {
      id: 3,
      title: "Shuttle Routes 11-15 Guidance",
      date: "Fresher Alert",
      category: "Shuttles",
      content: "Routes 11 through 15 serve as dedicated high-frequency shuttles connecting UET Main Campus to KSK New Campus."
    }
  ],

  routes: [
    // ==========================================
    // --- MAIN CAMPUS UPDATED ROUTES (1 to 22) ---
    // Morning Arrivals ONLY
    // ==========================================
    {
      id: "main-01",
      routeNo: "Route 1",
      campusId: "main",
      campus: "Main",
      name: "Ring Road, Askari & Dharampura",
      startPoint: "Ring Road",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #1",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M01",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus GT Road.",
      stops: [
        { name: "Ring Road", time: "6:55 AM", lat: 31.5720, lng: 74.4150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Askari 10", time: "6:57 AM", lat: 31.5680, lng: 74.4020, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bahar Shah Gol Chakar", time: "7:00 AM", lat: 31.5650, lng: 74.3950, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Chongi 2 Gage", time: "7:02 AM", lat: 31.5620, lng: 74.3880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Joray Pul", time: "7:05 AM", lat: 31.5580, lng: 74.3820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Norani Stop", time: "7:07 AM", lat: 31.5540, lng: 74.3780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Askari 9", time: "7:10 AM", lat: 31.5380, lng: 74.3820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Sadar Gol Chakar", time: "7:12 AM", lat: 31.5490, lng: 74.3680, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Dharam Pura", time: "7:15 AM", lat: 31.5580, lng: 74.3620, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Dharampura"] },
        { name: "Dharam Pura Pul", time: "7:20 AM", lat: 31.5610, lng: 74.3600, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Link Road/ Raam Garh", time: "7:22 AM", lat: 31.5640, lng: 74.3580, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shahu Wari Hospital", time: "7:25 AM", lat: 31.5680, lng: 74.3550, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ganda Nala", time: "7:27 AM", lat: 31.5720, lng: 74.3530, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-02",
      routeNo: "Route 2",
      campusId: "main",
      campus: "Main",
      name: "Ring Road, Shad Bagh & Mughalpura Line",
      startPoint: "Ring Road",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #2",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M02",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Ring Road", time: "7:10 AM", lat: 31.5950, lng: 74.3850, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shad Bagh", time: "7:15 AM", lat: 31.5980, lng: 74.3520, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mughal Pura", time: "7:20 AM", lat: 31.5650, lng: 74.3750, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Mughalpura"] },
        { name: "Laal Pul", time: "7:23 AM", lat: 31.5685, lng: 74.3820, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Lal Pul", "Lal Pull", "Laal Pull"] },
        { name: "Mughal Pura Chowk", time: "7:25 AM", lat: 31.5660, lng: 74.3720, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Singh Pura", time: "7:28 AM", lat: 31.5790, lng: 74.3510, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-02a",
      routeNo: "Route 2A",
      campusId: "main",
      campus: "Main",
      name: "Jallo Mor, Darogha Wala & Shalamar Line",
      startPoint: "Jallo Mor",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #2A",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M02A",
      arrivalTime: "07:45 AM",
      notes: "Morning line connecting GT Road eastern sector & Jallo Mor.",
      stops: [
        { name: "Jallo Mor", time: "6:45 AM", lat: 31.5850, lng: 74.4750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bata Factory", time: "6:49 AM", lat: 31.5840, lng: 74.4620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Raam Pura", time: "6:53 AM", lat: 31.5830, lng: 74.4510, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Munawa", time: "6:57 AM", lat: 31.5820, lng: 74.4400, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kot Kambo", time: "7:01 AM", lat: 31.5815, lng: 74.4300, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bagh Wali Puli", time: "7:05 AM", lat: 31.5810, lng: 74.4210, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Yadgarh", time: "7:08 AM", lat: 31.5805, lng: 74.4120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Swettar Mill", time: "7:11 AM", lat: 31.5800, lng: 74.4050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Quaid-e-Azam Interchange", time: "7:14 AM", lat: 31.5800, lng: 74.3980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Chongi", time: "7:17 AM", lat: 31.5805, lng: 74.3910, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Momin Pura", time: "7:20 AM", lat: 31.5810, lng: 74.3850, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Salamat Pura", time: "7:23 AM", lat: 31.5800, lng: 74.4020, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Darogha Wala", time: "7:26 AM", lat: 31.5815, lng: 74.3910, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Dhobi Ghat", time: "7:29 AM", lat: 31.5820, lng: 74.3800, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mint Gate", time: "7:32 AM", lat: 31.5825, lng: 74.3750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Suk Nehar", time: "7:35 AM", lat: 31.5825, lng: 74.3720, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shalamar Bagh", time: "7:38 AM", lat: 31.5830, lng: 74.3680, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-03",
      routeNo: "Route 3",
      campusId: "main",
      campus: "Main",
      name: "Defence Mor, Cantt & Sadar Line",
      startPoint: "Defence Mor",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #3",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M03",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Defence Mor", time: "6:40 AM", lat: 31.4920, lng: 74.3480, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mian Bolay Wala", time: "6:42 AM", lat: 31.4880, lng: 74.3510, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Adil Hospital", time: "6:43 AM", lat: 31.4860, lng: 74.3550, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bilal Store", time: "6:48 AM", lat: 31.4810, lng: 74.3610, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Laalak Chowk", time: "6:55 AM", lat: 31.4720, lng: 74.3750, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Laal Pull", "Lal Pull"] },
        { name: "Police Choki", time: "7:00 AM", lat: 31.4780, lng: 74.3810, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "LESCO", time: "7:05 AM", lat: 31.4820, lng: 74.3850, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Total Pump", time: "7:07 AM", lat: 31.4850, lng: 74.3890, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Punjab Society", time: "7:12 AM", lat: 31.4680, lng: 74.3980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Defence Mor", time: "7:20 AM", lat: 31.4920, lng: 74.3480, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Cantt", time: "7:23 AM", lat: 31.5210, lng: 74.3750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Girja Chowk", time: "7:25 AM", lat: 31.5350, lng: 74.3680, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Sadar Chowk", time: "7:30 AM", lat: 31.5490, lng: 74.3610, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-04",
      routeNo: "Route 4",
      campusId: "main",
      campus: "Main",
      name: "R.A. Bazar, Walton & Fortress Stadium Line",
      startPoint: "R. A. Bazar",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #4",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M04",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "R. A. Bazar", time: "6:45 AM", lat: 31.5280, lng: 74.3620, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["RA Bazar", "R A Bazaar", "RA Bazaar"] },
        { name: "Ali Park Mor", time: "6:47 AM", lat: 31.5250, lng: 74.3580, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Naka CMH", time: "6:50 AM", lat: 31.5210, lng: 74.3540, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "R. A. Bazar", time: "6:53 AM", lat: 31.5280, lng: 74.3620, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["RA Bazar", "R A Bazaar", "RA Bazaar"] },
        { name: "Workshop Stop Walton road", time: "7:00 AM", lat: 31.4950, lng: 74.3520, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Walton Stop", time: "7:05 AM", lat: 31.4880, lng: 74.3500, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "School Stop", time: "7:08 AM", lat: 31.4910, lng: 74.3550, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Koray Pind", time: "7:10 AM", lat: 31.4950, lng: 74.3600, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shami Road", time: "7:15 AM", lat: 31.5180, lng: 74.3680, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Fortress Stadium", time: "7:20 AM", lat: 31.5310, lng: 74.3650, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Zafar Ali Road", time: "7:23 AM", lat: 31.5380, lng: 74.3550, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-05",
      routeNo: "Route 5",
      campusId: "main",
      campus: "Main",
      name: "General Hospital, Kot Lakhpat & Model Town Line",
      startPoint: "General Hospital",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #5",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M05",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "General Hospital", time: "6:50 AM", lat: 31.4720, lng: 74.3580, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Chongi Amer Sidhu", time: "6:52 AM", lat: 31.4580, lng: 74.3620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kot Lakhpat Station", time: "6:55 AM", lat: 31.4650, lng: 74.3410, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Treet Blade Factory", time: "6:59 AM", lat: 31.4610, lng: 74.3350, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mochi Pura Link Road", time: "7:02 AM", lat: 31.4520, lng: 74.3150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Model Town Perchi", time: "7:05 AM", lat: 31.4750, lng: 74.3210, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "R-Block Model Town", time: "7:06 AM", lat: 31.4780, lng: 74.3240, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Link Mor Model Town", time: "7:10 AM", lat: 31.4820, lng: 74.3280, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "A-Block Markeet", time: "7:15 AM", lat: 31.4890, lng: 74.3250, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Model Town Mor", time: "7:20 AM", lat: 31.4980, lng: 74.3320, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-06",
      routeNo: "Route 6",
      campusId: "main",
      campus: "Main",
      name: "Nursery & Green Town Line",
      startPoint: "Nursery Stop",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #6",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M06",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Nursery Stop", time: "6:50 AM", lat: 31.4420, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Green Town Bazar", time: "6:55 AM", lat: 31.4380, lng: 74.3010, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Green Town Bazaar"] },
        { name: "Choras Tanki", time: "7:00 AM", lat: 31.4350, lng: 74.2950, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Nala Girja Stop", time: "7:13 AM", lat: 31.4410, lng: 74.2980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Nursery", time: "7:15 AM", lat: 31.4420, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Gol Chakar Model Town", time: "7:18 AM", lat: 31.4850, lng: 74.3250, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-07",
      routeNo: "Route 7",
      campusId: "main",
      campus: "Main",
      name: "Nishtar Colony & Ferozepur Road Line",
      startPoint: "Nishtar Colony",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #7",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M07",
      arrivalTime: "07:40 AM",
      notes: "Morning Arrival: 07:40 AM at UET Main Campus.",
      stops: [
        { name: "Nishtar Colony", time: "6:55 AM", lat: 31.4392, lng: 74.3645, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Waheed Colony", time: "7:00 AM", lat: 31.4480, lng: 74.3620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Venus society", time: "7:03 AM", lat: 31.4550, lng: 74.3610, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Atteri", time: "7:05 AM", lat: 31.4610, lng: 74.3590, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bank Stop", time: "7:07 AM", lat: 31.4680, lng: 74.3570, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Chungi", time: "7:10 AM", lat: 31.4750, lng: 74.3550, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ghazi Road", time: "7:12 AM", lat: 31.4810, lng: 74.3520, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Qainchi", time: "7:15 AM", lat: 31.4880, lng: 74.3490, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ghulab Devi", time: "7:20 AM", lat: 31.4990, lng: 74.3420, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:40 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-08",
      routeNo: "Route 8",
      campusId: "main",
      campus: "Main",
      name: "Shoukat Khanam, Johar Town & Main Market Line",
      startPoint: "Shoukat Khanam",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #8",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M08",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Shoukat Khanam", time: "6:50 AM", lat: 31.4620, lng: 74.2690, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shouq Chowk", time: "6:52 AM", lat: 31.4670, lng: 74.2790, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Allah Hoo Chowk", time: "7:00 AM", lat: 31.4690, lng: 74.2820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Jinnah Hospital", time: "7:10 AM", lat: 31.4850, lng: 74.2980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Fardoos Markeet", time: "7:15 AM", lat: 31.5050, lng: 74.3520, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Hussain Chowk", time: "7:20 AM", lat: 31.5090, lng: 74.3460, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Main Market", time: "7:25 AM", lat: 31.5180, lng: 74.3490, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-09",
      routeNo: "Route 9",
      campusId: "main",
      campus: "Main",
      name: "Wapda Town & College Line",
      startPoint: "Wapda Town",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #9",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M09",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Wapda Town", time: "6:55 AM", lat: 31.4390, lng: 74.2690, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "HBL office", time: "6:57 AM", lat: 31.4420, lng: 74.2710, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Cakes and Bakes bakery", time: "6:58 AM", lat: 31.4450, lng: 74.2730, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mosque Chowk", time: "7:00 AM", lat: 31.4480, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Govt. College", time: "7:03 AM", lat: 31.4520, lng: 74.2790, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Wapda Town Gol Chakar Outside", time: "7:05 AM", lat: 31.4560, lng: 74.2830, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-10",
      routeNo: "Route 10",
      campusId: "main",
      campus: "Main",
      name: "Ghazi Chowk, UMT & Khokhar Line",
      startPoint: "Ghazi Chowk",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #10",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M10",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Ghazi Chowk", time: "7:00 AM", lat: 31.4430, lng: 74.2740, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Gondal Chowk", time: "7:02 AM", lat: 31.4450, lng: 74.2760, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Butt Chowk", time: "7:04 AM", lat: 31.4470, lng: 74.2780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Al jannat chowk", time: "7:06 AM", lat: 31.4510, lng: 74.2880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "U M T", time: "7:08 AM", lat: 31.4560, lng: 74.2920, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Khokhar Chowk", time: "7:10 AM", lat: 31.4600, lng: 74.2660, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ghangh chowk", time: "7:12 AM", lat: 31.4620, lng: 74.2700, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Aslam Chowk", time: "7:45 AM", lat: 31.4680, lng: 74.2780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-11",
      routeNo: "Route 11",
      campusId: "main",
      campus: "Main",
      name: "Akbar Chowk, Muslim Town & Ichra Line",
      startPoint: "Akbar Chowk",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #11",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M11",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Akbar Chowk", time: "7:00 AM", lat: 31.4610, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Gormay chowk", time: "7:04 AM", lat: 31.4650, lng: 74.3080, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Nes Pak", time: "7:05 AM", lat: 31.4680, lng: 74.3100, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "School Stop", time: "7:07 AM", lat: 31.4720, lng: 74.3120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Beheeka Mor", time: "7:13 AM", lat: 31.5080, lng: 74.3020, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Naqsha Stop", time: "7:17 AM", lat: 31.5120, lng: 74.3100, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Muslim Town Mor", time: "7:20 AM", lat: 31.5150, lng: 74.3180, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Achra Mor", time: "7:23 AM", lat: 31.5280, lng: 74.3210, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shama Stop", time: "7:25 AM", lat: 31.5350, lng: 74.3180, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Abid Market", time: "7:30 AM", lat: 31.5420, lng: 74.3150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ganga ram markeet", time: "7:33 AM", lat: 31.5480, lng: 74.3120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-12",
      routeNo: "Route 12",
      campusId: "main",
      campus: "Main",
      name: "Hussaini Market, Expo Center & Doctor Hospital Line",
      startPoint: "Hussaini Markeet",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #12",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M12",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Hussaini Markeet", time: "6:58 AM", lat: 31.4650, lng: 74.2510, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "CNG Pump", time: "7:00 AM", lat: 31.4660, lng: 74.2550, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Expo Center", time: "7:03 AM", lat: 31.4680, lng: 74.2580, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Khokhar Chowk", time: "7:08 AM", lat: 31.4600, lng: 74.2660, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "School Stop", time: "7:10 AM", lat: 31.4650, lng: 74.2700, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Doctor Hospital", time: "7:12 AM", lat: 31.4780, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Wafaqi Colony", time: "7:15 AM", lat: 31.4820, lng: 74.2780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Punjab University", time: "7:22 AM", lat: 31.4950, lng: 74.2980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Laal Puli", time: "7:25 AM", lat: 31.5685, lng: 74.3820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mall Road", time: "7:27 AM", lat: 31.5580, lng: 74.3250, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mayo Garden", time: "7:35 AM", lat: 31.5650, lng: 74.3350, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Asif Center", time: "7:37 AM", lat: 31.5690, lng: 74.3420, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Sardar H/S", time: "7:40 AM", lat: 31.5740, lng: 74.3480, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-13",
      routeNo: "Route 13",
      campusId: "main",
      campus: "Main",
      name: "Multan Chungi, Kareem Block & Shadman Line",
      startPoint: "Multan Chungi",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #13",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M13",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Multan Chungi", time: "7:04 AM", lat: 31.5050, lng: 74.2850, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Hathi Chowk", time: "7:06 AM", lat: 31.5080, lng: 74.2880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mustafa Town", time: "7:08 AM", lat: 31.5120, lng: 74.2820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kareem Block", time: "7:10 AM", lat: 31.5180, lng: 74.2800, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Sikandar Block", time: "7:13 AM", lat: 31.5210, lng: 74.2820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Raza Block", time: "7:16 AM", lat: 31.5020, lng: 74.2880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Science College", time: "7:17 AM", lat: 31.5250, lng: 74.2920, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shadman under pas", time: "7:25 AM", lat: 31.5410, lng: 74.3180, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Jinnah Bagh Gate", time: "7:30 AM", lat: 31.5550, lng: 74.3210, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Devas Road", time: "7:35 AM", lat: 31.5620, lng: 74.3280, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-14",
      routeNo: "Route 14",
      campusId: "main",
      campus: "Main",
      name: "Iqbal Town, Moon Market & Sabzazar Line",
      startPoint: "Allama Iqbal Town Tainki # 4",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #14",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M14",
      arrivalTime: "07:50 AM",
      notes: "Morning Arrival: 07:50 AM at UET Main Campus.",
      stops: [
        { name: "Allama Iqbal Town Tainki # 4", time: "6:55 AM", lat: 31.5180, lng: 74.2850, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Moon Markeet", time: "7:00 AM", lat: 31.5210, lng: 74.2820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kali Kothi Stop", time: "7:02 AM", lat: 31.5240, lng: 74.2780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Darbar Stop Sabzazar", time: "7:04 AM", lat: 31.5280, lng: 74.2700, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ground Stop", time: "7:06 AM", lat: 31.5220, lng: 74.2720, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Liaqat Chowk", time: "7:10 AM", lat: 31.5180, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:50 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-15",
      routeNo: "Route 15",
      campusId: "main",
      campus: "Main",
      name: "Akbari Store, Multan Road & Awan Town Line",
      startPoint: "Akbari Store",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #15",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M15",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Akbari Store", time: "6:50 AM", lat: 31.5020, lng: 74.2620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Dubai Chowk", time: "6:52 AM", lat: 31.5050, lng: 74.2650, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kareem Market", time: "6:55 AM", lat: 31.5180, lng: 74.2800, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Multan Road", time: "7:02 AM", lat: 31.5120, lng: 74.2720, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Awan Town", time: "7:03 AM", lat: 31.5080, lng: 74.2680, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shah Noor", time: "7:09 AM", lat: 31.5150, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kaleem Mor", time: "7:12 AM", lat: 31.5200, lng: 74.2780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-16",
      routeNo: "Route 16",
      campusId: "main",
      campus: "Main",
      name: "Raiwind Bypass, EME & Thokar Line",
      startPoint: "Ali Hospital",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #16",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M16",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Ali Hospital", time: "6:45 AM", lat: 31.4550, lng: 74.2250, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Rai wand By Pas", time: "6:48 AM", lat: 31.4580, lng: 74.2280, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Pasco Society", time: "6:50 AM", lat: 31.4620, lng: 74.2320, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "EME", time: "6:52 AM", lat: 31.4650, lng: 74.2380, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shah Pur Kanjaraan", time: "6:57 AM", lat: 31.4680, lng: 74.2410, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Park View", time: "7:00 AM", lat: 31.4700, lng: 74.2400, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Thokar", time: "7:03 AM", lat: 31.4730, lng: 74.2420, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Doctor Hospital", time: "7:10 AM", lat: 31.4780, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-17",
      routeNo: "Route 17",
      campusId: "main",
      campus: "Main",
      name: "Orphanage, Band Road & Samanabad Line",
      startPoint: "Orphanage",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #17",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M17",
      arrivalTime: "07:50 AM",
      notes: "Morning Arrival: 07:50 AM at UET Main Campus.",
      stops: [
        { name: "Orphanage", time: "7:00 AM", lat: 31.5180, lng: 74.2680, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shahzan Factory", time: "7:05 AM", lat: 31.5210, lng: 74.2720, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Niazi Adda", time: "7:07 AM", lat: 31.5250, lng: 74.2780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Band Road", time: "7:09 AM", lat: 31.6090, lng: 74.3029, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Double Road", time: "7:13 AM", lat: 31.5950, lng: 74.3080, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Park Stop Mini Market", time: "7:15 AM", lat: 31.5750, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Park Stop", time: "7:17 AM", lat: 31.5680, lng: 74.3090, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shanai Mall", time: "7:20 AM", lat: 31.5520, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Samanabad Mor", time: "7:25 AM", lat: 31.5346, lng: 74.2941, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:50 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-18",
      routeNo: "Route 18",
      campusId: "main",
      campus: "Main",
      name: "Chuburji, Islamia Park & Shimla Pahari Line",
      startPoint: "Pehla Gool Chakar",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #18",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M18",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Pehla Gool Chakar", time: "7:05 AM", lat: 31.5450, lng: 74.2950, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Second Gool Chakar", time: "7:07 AM", lat: 31.5470, lng: 74.2980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bohar Wala Chowk", time: "7:10 AM", lat: 31.5490, lng: 74.3010, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Choudhry Colony", time: "7:13 AM", lat: 31.5510, lng: 74.3030, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shabab Chowk", time: "7:15 AM", lat: 31.5530, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Pakki Thathi", time: "7:18 AM", lat: 31.5550, lng: 74.3080, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bastami Road", time: "7:21 AM", lat: 31.5570, lng: 74.3100, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shairan Wali Kothi", time: "7:23 AM", lat: 31.5590, lng: 74.3120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "School Stop", time: "7:25 AM", lat: 31.5610, lng: 74.3140, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Gool Chakar Nala", time: "7:26 AM", lat: 31.5620, lng: 74.3150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ponch Road Islamia", time: "7:28 AM", lat: 31.5630, lng: 74.3170, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Islamia Park 1st Gol Chakar", time: "7:30 AM", lat: 31.5640, lng: 74.3190, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mosque", time: "7:30 AM", lat: 31.5645, lng: 74.3200, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Quarter", time: "7:31 AM", lat: 31.5650, lng: 74.3210, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Chaburji", time: "7:32 AM", lat: 31.5510, lng: 74.3020, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mian Sb", time: "7:33 AM", lat: 31.5520, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Abid Markeet", time: "7:35 AM", lat: 31.5420, lng: 74.3150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Waris Road", time: "7:37 AM", lat: 31.5450, lng: 74.3220, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ganga Raam", time: "7:40 AM", lat: 31.5480, lng: 74.3120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shimla Phari", time: "7:45 AM", lat: 31.5620, lng: 74.3350, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-19",
      routeNo: "Route 19",
      campusId: "main",
      campus: "Main",
      name: "Ismailpura, Anarkali & Kachari Line",
      startPoint: "Local Govt. Complex",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #19",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M19",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Local Govt. Complex", time: "7:15 AM", lat: 31.5590, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Main Bazar Islam Pura", time: "7:18 AM", lat: 31.5660, lng: 74.2957, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Islampura", "Islam Pura", "Ismailpura", "Main Bazaar Islam Pura"] },
        { name: "District Kachari", time: "7:25 AM", lat: 31.5640, lng: 74.3140, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Anarkali", time: "7:30 AM", lat: 31.5679, lng: 74.3106, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Chaman Ice Cream", time: "7:32 AM", lat: 31.5710, lng: 74.3200, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-20",
      routeNo: "Route 20",
      campusId: "main",
      campus: "Main",
      name: "Kot Abdul Malik, Begum Kot & Shad Bagh Line",
      startPoint: "Kot Abdul Malik",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #20",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M20",
      arrivalTime: "07:50 AM",
      notes: "Morning Arrival: 07:50 AM at UET Main Campus.",
      stops: [
        { name: "Kot Abdul Malik", time: "7:00 AM", lat: 31.6250, lng: 74.2450, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Baddu Puli", time: "7:02 AM", lat: 31.6280, lng: 74.2520, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Beghum Kot", time: "7:03 AM", lat: 31.6310, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Yousaf Park", time: "7:05 AM", lat: 31.6350, lng: 74.2820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Rustam Factory", time: "7:08 AM", lat: 31.6380, lng: 74.2880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "25 # Stop", time: "7:10 AM", lat: 31.6410, lng: 74.2920, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "G A Musa", time: "7:12 AM", lat: 31.6450, lng: 74.2980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ring Road", time: "7:18 AM", lat: 31.6210, lng: 74.3150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Amir Road", time: "7:25 AM", lat: 31.6050, lng: 74.3320, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shad Bagh Gol Chakar", time: "7:30 AM", lat: 31.5980, lng: 74.3520, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Shad Bagh", time: "7:33 AM", lat: 31.6010, lng: 74.3550, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Taj Pura", time: "7:37 AM", lat: 31.5950, lng: 74.3620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Na Khuda Chowk", time: "7:40 AM", lat: 31.5910, lng: 74.3480, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:50 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-21",
      routeNo: "Route 21",
      campusId: "main",
      campus: "Main",
      name: "Narowal Chowk, KSK Toll Plaza & Lari Adda Line",
      startPoint: "Narowal Chowk",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #21",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M21",
      arrivalTime: "07:50 AM",
      notes: "Morning Arrival: 07:50 AM at UET Main Campus.",
      stops: [
        { name: "Narowal Chowk", time: "6:45 AM", lat: 31.8500, lng: 74.3200, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Offier Mil", time: "6:55 AM", lat: 31.8100, lng: 74.3120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ravi Riyan", time: "7:00 AM", lat: 31.7650, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "KSK Pump/ Tool Plaza", time: "7:10 AM", lat: 31.7310, lng: 74.2980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Imamia Colony/Phatak", time: "7:20 AM", lat: 31.6420, lng: 74.2980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Lari Adda", time: "7:40 AM", lat: 31.5910, lng: 74.3290, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:50 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "main-22",
      routeNo: "Route 22",
      campusId: "main",
      campus: "Main",
      name: "Matchis Factory, Shahdara & Data Darbar Line",
      startPoint: "Matchis Factory",
      endPoint: "UET Main Campus",
      driverName: "Main Campus Driver #22",
      driverPhone: "0304-0165776",
      vehicleNo: "UET-M22",
      arrivalTime: "07:45 AM",
      notes: "Morning Arrival: 07:45 AM at UET Main Campus.",
      stops: [
        { name: "Matchis Factory", time: "7:10 AM", lat: 31.6350, lng: 74.2950, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Thana Stop", time: "7:11 AM", lat: 31.6310, lng: 74.2920, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shadi Hall", time: "7:15 AM", lat: 31.6250, lng: 74.2880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Station Shahdra", time: "7:18 AM", lat: 31.6210, lng: 74.2890, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kachari Stop", time: "7:20 AM", lat: 31.6150, lng: 74.2920, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shahdra Mor", time: "7:23 AM", lat: 31.6110, lng: 74.2950, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kasur Pura", time: "7:25 AM", lat: 31.5950, lng: 74.3010, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Metro Stop", time: "7:28 AM", lat: 31.5850, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Data Darbar", time: "7:30 AM", lat: 31.5780, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shalami Markeet", time: "7:33 AM", lat: 31.5810, lng: 74.3180, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Delhi Gate", time: "7:36 AM", lat: 31.5820, lng: 74.3250, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "UET Main Campus", time: "7:45 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },

    // ==========================================
    // --- KSK / NEW CAMPUS ROUTES (1 - 15) ---
    // Morning Arrivals ONLY
    // ==========================================
    {
      id: "ksk-01",
      routeNo: "01",
      campusId: "ksk",
      campus: "KSK",
      name: "Harbanspura & Mughalpura Line",
      startPoint: "Harbanspura",
      endPoint: "KSK New Campus",
      driverName: "Mr. Ejaz Ahmed",
      driverPhone: "0323-4513997",
      vehicleNo: "LEJ-148",
      arrivalTime: "07:50 AM",
      notes: "Covers Canal Bank Road, Taj Bagh & Mughalpura flyover.",
      stops: [
        { name: "Harbanspura", time: "6:50 AM", lat: 31.5721, lng: 74.4215, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Madina Town", time: "6:58 AM", lat: 31.5750, lng: 74.4120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Taj Bagh", time: "7:05 AM", lat: 31.5695, lng: 74.4050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Fateh Garh", time: "7:08 AM", lat: 31.5710, lng: 74.3980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Pull", time: "7:09 AM", lat: 31.5700, lng: 74.3890, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Laal Pull", "Lal Pull"] },
        { name: "Mughal Pura", time: "7:18 AM", lat: 31.5650, lng: 74.3750, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Mughalpura"] },
        { name: "Dharam Pura", time: "7:25 AM", lat: 31.5580, lng: 74.3620, coordinateStatus: "unverified", placeId: null, source: null, aliases: ["Dharampura"] },
        { name: "New Campus", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-02",
      routeNo: "02",
      campusId: "ksk",
      campus: "KSK",
      name: "Nishtar Colony, Defence Morr & Kalma Line",
      startPoint: "Nishtar Colony",
      endPoint: "KSK New Campus",
      driverName: "Mr. Abdul Basit",
      driverPhone: "0308-4973489",
      vehicleNo: "LEA-6833",
      arrivalTime: "07:50 AM",
      notes: "Main Ferozepur Road arterial route connecting Model Town, Kalma Chowk & Ichra.",
      stops: [
        { name: "Nishtar Colony", time: "6:30 AM", lat: 31.4392, lng: 74.3645, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Chungi Amar sidhu", time: "6:35 AM", lat: 31.4580, lng: 74.3620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "General Hospital", time: "6:40 AM", lat: 31.4720, lng: 74.3580, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Qainchi Stop", time: "6:42 AM", lat: 31.4810, lng: 74.3540, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Walton Stop", time: "6:44 AM", lat: 31.4880, lng: 74.3500, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Defence Mor", time: "6:45 AM", lat: 31.4920, lng: 74.3480, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Firdous Market", time: "6:52 AM", lat: 31.5050, lng: 74.3520, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Hussain chowk", time: "6:56 AM", lat: 31.5090, lng: 74.3460, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kalma Chowk", time: "7:00 AM", lat: 31.5040, lng: 74.3315, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ichra", time: "7:12 AM", lat: 31.5280, lng: 74.3210, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Qartba Chowk", time: "7:22 AM", lat: 31.5450, lng: 74.3120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-03",
      routeNo: "03",
      campusId: "ksk",
      campus: "KSK",
      name: "Mochi Pura & Wapda Town Line",
      startPoint: "Mochi pura",
      endPoint: "KSK New Campus",
      driverName: "Mr. M. Sibtain",
      driverPhone: "0305-4143017",
      vehicleNo: "LEJ-143",
      arrivalTime: "07:50 AM",
      notes: "Covers Township, Peco Road, Akbar Chowk & Wapda Town.",
      stops: [
        
        { name: "Akbar chowk", time: "6:36 AM", lat: 31.4610, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "M. Ali chowk", time: "6:40 AM", lat: 31.4580, lng: 74.2980, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Khokhar chowk", time: "6:42 AM", lat: 31.4550, lng: 74.2920, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Al-Jannat Chowk", time: "6:44 AM", lat: 31.4510, lng: 74.2880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ameer Chowk", time: "6:45 AM", lat: 31.4480, lng: 74.2820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Butt chowk", time: "6:47 AM", lat: 31.4450, lng: 74.2780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ghazi chowk", time: "6:48 AM", lat: 31.4430, lng: 74.2740, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Wapda Town", time: "6:50 AM", lat: 31.4390, lng: 74.2690, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Abu bakar chowk", time: "6:55 AM", lat: 31.4410, lng: 74.2650, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Edhi Road", time: "7:00 AM", lat: 31.4480, lng: 74.2580, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-04",
      routeNo: "04",
      campusId: "ksk",
      campus: "KSK",
      name: "Muslim Town & Sabzazar Line",
      startPoint: "Muslim Town",
      endPoint: "KSK New Campus",
      driverName: "Zahid Mehmood",
      driverPhone: "0321-4990158",
      vehicleNo: "LZR-2351",
      arrivalTime: "07:50 AM",
      notes: "Passes through Wahdat Road, Sabzazar, Babu Sabu & Shahdara Flyover.",
      stops: [
        { name: "Muslim Town", time: "6:40 AM", lat: 31.5150, lng: 74.3180, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Naqsha Stop", time: "6:44 AM", lat: 31.5120, lng: 74.3100, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Baikhe wala", time: "6:46 AM", lat: 31.5080, lng: 74.3020, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Wahdat Road", time: "6:48 AM", lat: 31.5050, lng: 74.2950, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Raza Block", time: "6:50 AM", lat: 31.5020, lng: 74.2880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kharak Stop", time: "6:55 AM", lat: 31.5090, lng: 74.2810, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Liaqat chowk", time: "7:00 AM", lat: 31.5180, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Sabzazar", time: "7:05 AM", lat: 31.5280, lng: 74.2700, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Babu Sabu", time: "7:10 AM", lat: 31.5420, lng: 74.2760, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shahdara Station", time: "7:30 AM", lat: 31.6210, lng: 74.2890, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-05",
      routeNo: "05",
      campusId: "ksk",
      campus: "KSK",
      name: "Flat Stop, Samanabad & Secretariat Line",
      startPoint: "Flat Stop",
      endPoint: "KSK New Campus",
      driverName: "Mr. M. Arshad",
      driverPhone: "0322-4250804",
      vehicleNo: "LZB-2607",
      arrivalTime: "07:50 AM",
      notes: "Covers Yateem Khana, Chaburji, MAO College, Secretariat & Data Darbar.",
      stops: [
        { name: "Flat Stop", time: "6:40 AM", lat: 31.5180, lng: 74.2620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Scheme Morr", time: "6:50 AM", lat: 31.5220, lng: 74.2690, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Yateem Khana", time: "7:00 AM", lat: 31.5290, lng: 74.2780, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Morr Samanabad", time: "7:05 AM", lat: 31.5350, lng: 74.2890, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Chowk Chaburji", time: "7:12 AM", lat: 31.5510, lng: 74.3020, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "MAO College", time: "7:18 AM", lat: 31.5580, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Secretariat", time: "7:25 AM", lat: 31.5660, lng: 74.3080, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Data Darbar", time: "7:30 AM", lat: 31.5780, lng: 74.3050, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-06",
      routeNo: "06",
      campusId: "ksk",
      campus: "KSK",
      name: "Mochi Pura, Johar Town & Thokar Line",
      startPoint: "Mochi Pura",
      endPoint: "KSK New Campus",
      driverName: "Mr. Rehmat Ali",
      driverPhone: "0300-4112131",
      vehicleNo: "LRT-2034",
      arrivalTime: "07:50 AM",
      notes: "Main Johar Town & Canal Road line via G-1 Market & Thokar Niaz Baig.",
      stops: [
        { name: "Mochi Pura", time: "6:30 AM", lat: 31.4720, lng: 74.2910, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Allah Hoo Chowk", time: "6:38 AM", lat: 31.4690, lng: 74.2820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shadiwal Chowk", time: "6:42 AM", lat: 31.4650, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "G-1 Market", time: "6:45 AM", lat: 31.4630, lng: 74.2710, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Khokhar Chowk", time: "6:50 AM", lat: 31.4600, lng: 74.2660, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Expo Centre", time: "6:55 AM", lat: 31.4680, lng: 74.2580, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Thokar Niaz Baig", time: "7:00 AM", lat: 31.4730, lng: 74.2420, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Hanjarwal", time: "N/A", lat: 31.4770, lng: 74.2470, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-07",
      routeNo: "07",
      campusId: "ksk",
      campus: "KSK",
      name: "Burj Attari, Shahdara & Begum Kot Line",
      startPoint: "Burj Attari",
      endPoint: "KSK New Campus",
      driverName: "Mr. M. Nasir",
      driverPhone: "0300-8104930",
      vehicleNo: "LZR-2349",
      arrivalTime: "07:50 AM",
      notes: "Covers Faiz Pur Motorway side, Shahdara & Rachna Town.",
      stops: [
        { name: "Burj Attari", time: "6:50 AM", lat: 31.6050, lng: 74.2150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Faiz Pur", time: "6:55 AM", lat: 31.6110, lng: 74.2320, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Phool Mandi", time: "7:00 AM", lat: 31.6180, lng: 74.2510, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Begum Kot", time: "7:20 AM", lat: 31.6310, lng: 74.2750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shahdara", time: "7:25 AM", lat: 31.6250, lng: 74.2880, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-08",
      routeNo: "08",
      campusId: "ksk",
      campus: "KSK",
      name: "Bismillah Scheme, Shalimar & Singh Pura Line",
      startPoint: "Bismillah scheme",
      endPoint: "KSK New Campus",
      driverName: "Mr. Khadim Hussain",
      driverPhone: "0322-3899181",
      vehicleNo: "LEE-9715",
      arrivalTime: "07:50 AM",
      notes: "GT Road eastern sector route covering Darogawala & Shalimar Chowk.",
      stops: [
        { name: "Bismillah scheme", time: "6:30 AM", lat: 31.5850, lng: 74.4550, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Yadgar Shuhda", time: "6:40 AM", lat: 31.5820, lng: 74.4320, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Adda Shabeel", time: "6:48 AM", lat: 31.5810, lng: 74.4150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Salamat Pura", time: "6:52 AM", lat: 31.5800, lng: 74.4020, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Darogawala", time: "6:55 AM", lat: 31.5815, lng: 74.3910, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Akhri minute", time: "6:58 AM", lat: 31.5820, lng: 74.3820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Souk Nahar", time: "6:59 AM", lat: 31.5825, lng: 74.3750, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Shalimar chowk", time: "7:00 AM", lat: 31.5830, lng: 74.3680, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Gaas mandi", time: "7:12 AM", lat: 31.5810, lng: 74.3580, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Singh Pura", time: "7:20 AM", lat: 31.5790, lng: 74.3510, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-09",
      routeNo: "09",
      campusId: "ksk",
      campus: "KSK",
      name: "Chan Da Qilla, Kamoki & Muridkey Line",
      startPoint: "Chan da qilla",
      endPoint: "KSK New Campus",
      driverName: "Mr. M. Arif",
      driverPhone: "0300-4797349",
      vehicleNo: "LZB-2606",
      arrivalTime: "07:50 AM",
      notes: "Northern GT Road express line from Gujranwala / Kamoki direction.",
      stops: [
        { name: "Chan da qilla", time: "6:40 AM", lat: 32.1310, lng: 74.1950, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kamoki", time: "6:55 AM", lat: 31.9760, lng: 74.2210, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Sadhoki", time: "7:05 AM", lat: 31.8850, lng: 74.2450, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Muridkey", time: "7:30 AM", lat: 31.8020, lng: 74.2620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-09a",
      routeNo: "9-A",
      campusId: "ksk",
      campus: "KSK",
      name: "Muridke, Ferozewala & Rachna Town Line",
      startPoint: "Muridke",
      endPoint: "KSK New Campus",
      driverName: "N/A",
      driverPhone: "N/A",
      vehicleNo: "N/A",
      arrivalTime: "N/A",
      notes: "Northern GT Road route via Muridke, Ferozewala & Rachna Town.",
      stops: [
        { name: "Muridke", time: "N/A", lat: 31.8020, lng: 74.2620, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mujahid Hotel", time: "N/A", lat: 31.7920, lng: 74.2660, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "HBL", time: "N/A", lat: 31.7850, lng: 74.2690, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bangla Puli", time: "N/A", lat: 31.7790, lng: 74.2730, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Officer Mill", time: "N/A", lat: 31.7730, lng: 74.2760, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "THQ", time: "N/A", lat: 31.7660, lng: 74.2800, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Mano Mill", time: "N/A", lat: 31.7590, lng: 74.2840, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ravi Rayan", time: "N/A", lat: 31.7520, lng: 74.2870, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "SA Gardens", time: "N/A", lat: 31.7450, lng: 74.2910, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kala Station", time: "N/A", lat: 31.7380, lng: 74.2940, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Kot Shahabuddin", time: "N/A", lat: 31.7320, lng: 74.2960, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Match Factory", time: "N/A", lat: 31.7250, lng: 74.2990, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Barkat Town", time: "N/A", lat: 31.7180, lng: 74.3020, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Imamia Colony", time: "N/A", lat: 31.7100, lng: 74.3060, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ferozewala", time: "N/A", lat: 31.7030, lng: 74.3090, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Rachna Town", time: "N/A", lat: 31.6960, lng: 74.3120, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Rana Town", time: "N/A", lat: 31.6880, lng: 74.3150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus", time: "N/A", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-10",
      routeNo: "10",
      campusId: "ksk",
      campus: "KSK",
      name: "Ghazi Road, Cantt & Railway Station Line",
      startPoint: "Ghazi Road",
      endPoint: "KSK New Campus",
      driverName: "Mr. Ansar Majeed",
      driverPhone: "0300-8831159",
      vehicleNo: "LRT-2036",
      arrivalTime: "07:50 AM",
      notes: "Covers Lahore Cantt, Sadar Gol Chakar, Garhi Shahu & Railway Station.",
      stops: [
        { name: "Ghazi Road", time: "6:30 AM", lat: 31.4780, lng: 74.3720, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Bhatta chowk", time: "6:45 AM", lat: 31.4820, lng: 74.3910, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Barki Interchange", time: "6:52 AM", lat: 31.5050, lng: 74.4210, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Ranger Hadquarter", time: "6:58 AM", lat: 31.5210, lng: 74.4150, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Murgi Khana", time: "7:04 AM", lat: 31.5310, lng: 74.3950, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Askari 9", time: "7:10 AM", lat: 31.5380, lng: 74.3820, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Sadar Gol Chakar", time: "7:18 AM", lat: 31.5490, lng: 74.3680, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    },
    {
      id: "ksk-11-15",
      routeNo: "11 - 15",
      campusId: "ksk",
      campus: "KSK",
      name: "Main Campus to KSK Shuttle Express (Buses 11, 12, 13, 14, 15)",
      startPoint: "UET Main Campus",
      endPoint: "KSK New Campus",
      driverName: "Transport Office Shuttles",
      driverPhone: "0304-0165776",
      vehicleNo: "Fleet 11-15",
      arrivalTime: "07:50 AM",
      notes: "Dedicated multi-bus inter-campus shuttles operating between Main Campus & KSK Campus.",
      stops: [
        { name: "Main Campus (GT Road)", time: "7:00 AM", lat: 31.5794, lng: 74.3562, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Tezab Ehata", time: "7:04 AM", lat: 31.5780, lng: 74.3480, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Station stairs", time: "7:07 AM", lat: 31.5730, lng: 74.3350, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Do Moria Pull", time: "7:10 AM", lat: 31.5820, lng: 74.3310, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Lari adda", time: "7:12 AM", lat: 31.5910, lng: 74.3290, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Yadgar Chowk", time: "7:14 AM", lat: 31.5920, lng: 74.3220, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Timber market", time: "7:15 AM", lat: 31.5980, lng: 74.3180, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "Batti chowk", time: "7:22 AM", lat: 31.6050, lng: 74.3080, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] },
        { name: "New Campus (KSK)", time: "7:50 AM", lat: 31.7295, lng: 74.2985, coordinateStatus: "unverified", placeId: null, source: null, aliases: [] }
      ]
    }
  ],

  faqs: [
    {
      q: "How can I obtain a UET Bus Pass?",
      a: "Bus passes are issued at the Transport Office (located near Main Hall at Main Campus, and Admin Block at KSK Campus). First-year students need their admission fee slip, two passport-sized photographs, and CNIC/B-Form copy."
    },
    {
      q: "What time should I arrive at my bus stop?",
      a: "You must arrive at least 5 to 10 minutes before the scheduled pickup time. UET buses follow strict timing constraints to reach campus by 07:45 AM (Main) and 07:50 AM (KSK)."
    },
    {
      q: "Are afternoon return times shown on this schedule?",
      a: "This schedule focuses exclusively on morning arrival routes to ensure students reach campus on time. For afternoon return departures, buses leave campus terminals at 04:15 PM daily."
    },
    {
      q: "Can Main Campus students ride the KSK shuttle buses?",
      a: "Yes! Shuttle Routes 11 to 15 are specifically designed to carry students and staff between Main Campus GT Road and KSK New Campus."
    },
    {
      q: "Who should I contact in case of lost belongings or driver queries?",
      a: "You can call the respective driver contact number listed on your route page, or contact the Chairman Transport Committee Mr. M. Mushtaq directly at 0304-0165776."
    }
  ]
};

// Popular area quick-select entries derived from actual bus stop coordinates.
// Each entry uses the coordinates of a real bus stop for GPS-distance matching.
const POPULAR_AREAS = [
  { name: "Harbanspura", lat: 31.5721, lng: 74.4215 },
  { name: "Mughalpura", lat: 31.5650, lng: 74.3750 },
  { name: "Defence Mor", lat: 31.4920, lng: 74.3480 },
  { name: "Nishtar Colony", lat: 31.4392, lng: 74.3645 },
  { name: "Model Town", lat: 31.4850, lng: 74.3250 },
  { name: "Wapda Town", lat: 31.4390, lng: 74.2690 },
  { name: "Johar Town", lat: 31.4690, lng: 74.2820 },
  { name: "Township / Akbar Chowk", lat: 31.4610, lng: 74.3050 },
  { name: "Thokar Niaz Baig", lat: 31.4730, lng: 74.2420 },
  { name: "Sabzazar", lat: 31.5280, lng: 74.2700 },
  { name: "Samanabad", lat: 31.5346, lng: 74.2941 },
  { name: "Shahdara", lat: 31.6250, lng: 74.2880 }
];
